name: Coverage %

on:
  push:
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
      VDIFFR_RUN_TESTS: "false"   # desactiva los snapshots de vdiffr en CI

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: any::covr
          needs: coverage

      - name: Install package (no vignettes)
        run: |
          R -q -e "install.packages('remotes', repos='https://cran.r-project.org')"
          R -q -e "remotes::install_local('.', dependencies=TRUE, upgrade='never', build=TRUE, build_vignettes=FALSE, INSTALL_opts=c('--no-multiarch','--with-keep.source'))"

      - name: Compute coverage %
        shell: bash
        run: |
          Rscript - <<'RS'
          tf <- list.files("tests/testthat", pattern="^test.*\\.R$", full.names=TRUE)
          tf <- tf[!grepl("visual", tf, ignore.case=TRUE)]
          pc <- covr::percent_coverage(covr::package_coverage(test_files = tf))
          cat(sprintf("%.2f%%\n", pc))
          RS
