name: Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      COVERAGE_MIN: "0"
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          use-public-rspm: true
      - name: Install deps
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: any::covr
          extra-packages: any::covr
          needs: coverage

      - name: Run tests and compute coverage
        run: |
          R -q -e "cov <- covr::package_coverage();
                   print(cov);
                   pc <- covr::percent_coverage(cov);
                   cat('Total coverage:', pc, '%\\n');
                   if (as.numeric(Sys.getenv('COVERAGE_MIN')) > 0 && pc < as.numeric(Sys.getenv('COVERAGE_MIN'))) {
                     stop(sprintf('Coverage %.2f%% is below threshold %s%%', pc, Sys.getenv('COVERAGE_MIN')))
                   }
                   covr::to_cobertura(cov, file='coverage.xml')"
      - name: Upload to Codecov
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
          verbose: true
