name: Coverage %

on:
  push:
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: any::covr
          needs: coverage

      - name: Install package (no vignettes)
        run: |
          R -q -e "install.packages('remotes', repos='https://cran.r-project.org')"
          R -q -e "remotes::install_local('.', dependencies=TRUE, upgrade='never', build=TRUE, build_vignettes=FALSE, INSTALL_opts=c('--no-multiarch','--with-keep.source'))"

      - name: Compute coverage %
        shell: bash
        run: |
          Rscript - <<'RS'
          files <- list.files("tests/testthat", pattern="^test.*\\.R$", full.names=TRUE)
          files <- files[!grepl("visual", files, ignore.case=TRUE)]
          tests_fn <- function() {
            if (length(files)) {
              testthat::test_dir("tests/testthat",
                                 filter = "^((?!visual).)*$",
                                 reporter = "silent")
            } else {
              message("No non-visual tests found.")
            }
          }
          cov <- covr::package_coverage(tests = tests_fn)
          pc  <- covr::percent_coverage(cov)
          cat(sprintf("%.2f%%\n", pc))
          RS
