name: R check + Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      # Solo necesario si el repo es privado:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          use-public-rspm: true

      - uses: r-lib/actions/setup-pandoc@v2

      # Esto resuelve automáticamente dependencias de R y del sistema (sysreqs)
      - name: Install R deps (with sysreqs)
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::rcmdcheck
            any::covr
          extra-packages: any::rcmdcheck, any::covr
          needs: check

      - name: R CMD check
        run: |
          R -q -e "rcmdcheck::rcmdcheck(args='--no-manual', error_on='warning')"

      - name: Generate coverage (Cobertura XML)
        run: |
          R -q -e "cov <- covr::package_coverage(); print(cov)"
          R -q -e "covr::to_cobertura(cov, file='coverage.xml')"

      - name: Upload to Codecov (only on main)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
          verbose: true
